### ISSUE TITLE
mac地址问题

### ISSUE THREAD

**Issue by lmz13411274381** [EspressifApp/EspBlufiForiOS#18]
我在设备端加了mac地址广播，在安卓手机上用工具看有广播的，在苹果的这个源码上扫描确看不见，只有uuid信息

**Comment by XuXiangJun** [comment]
iOS BLE 扫描不提供 Mac 信息的
除非你把 Mac 信息放到 BLE 广播的 Manufacturer Data 里，这样 iOS 也可以手动解析相关内容
