### ISSUE TITLE
Secret keys are being logged and showing inside log files

### ISSUE THREAD

**Issue by aizatomar** [EspressifApp/EspBlufiForiOS#19]
Hello. Will like to point out that secret keys are being logged out for production app in the BlufiClient file.
DH Secret and AES keys are being logged in the `negotiateSecurity` function. May I suggest wrapping these `NSLog` within an `#if DEBUG` scope so that these secret keys are not accidentally displayed in the log files inside a production app.

**Comment by XuXiangJun** [comment]
You are right. I will modify it today.
Thank you.

**Comment by aizatomar** [comment]
No problem. :)

Please update here when the fix has been released. Thank you. :)

**Comment by brunck** [comment]
This was fixed some time ago.
