### ISSUE TITLE
EspBlufi 文件丢失 Prefix.pch

### ISSUE THREAD

**Issue by KaneLanF** [EspressifApp/EspBlufiForiOS#7]
Prefix.pch文件丢失 无法编译

**Comment by Weijian-Espressif** [comment]
请参考 EspBlufiV1.1

**Comment by KaneLanF** [comment]
[EspBlufiV1.1.zip](https://github.com/EspressifApp/EspBlufiForiOS/files/2976227/EspBlufiV1.1.zip)
这个版可以正常使用 通讯加密逻辑需要自己封装。
