### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by KaneLanF** [EspressifApp/EspBlufiForiOS#8]
3个文件缺失  请检查依赖和配置文件后重新上传

**Comment by fanbaoying** [comment]
线上项目拉下来编译可以通过，请问是那三个文件缺失，编译报什么错误？

**Comment by KaneLanF** [comment]
![image](https://user-images.githubusercontent.com/13937314/54334355-b5a7f980-4660-11e9-8882-6eb87c436ecc.png)

**Comment by KaneLanF** [comment]
![](https://ws1.sinaimg.cn/large/006tKfTcgy1g12a9o51wyj30ie0920ta.jpg)

**Comment by KaneLanF** [comment]
![](https://ws1.sinaimg.cn/large/006tKfTcgy1g12abs7n7mj30vy0pgju9.jpg)

**Comment by KaneLanF** [comment]
![](https://ws2.sinaimg.cn/large/006tKfTcgy1g12ad3ipwwj30n00fmdg2.jpg)

**Comment by KaneLanF** [comment]
![](https://ws3.sinaimg.cn/large/006tKfTcgy1g12ae1mqiij30m90emq34.jpg)

**Comment by KaneLanF** [comment]
![](https://ws4.sinaimg.cn/large/006tKfTcgy1g12aehfa54j30lt0erglq.jpg)

**Comment by KaneLanF** [comment]
![](https://ws3.sinaimg.cn/large/006tKfTcgy1g12agudhx5j30wg0gxaag.jpg)

**Comment by KaneLanF** [comment]
工程目录结构混乱 无法使用

**Comment by KaneLanF** [comment]
https://github.com/EspressifApp/EspBlufiForiOS/issues/8?_pjax=%23js-repo-pjax-container

您好  已在GitHub提交issue截图  贵公司去年上传的版本 直接崩溃有好几个崩溃点 经过好几轮交涉 修正了崩溃问题 但在使用便利性方便仍然与同平台提供的Android版本有很大差异 【Android版本有完整的封装  Demo版本通信加密 自定义协议都有比较好的支持 Demo 代码整齐 页面下方有2排按钮 逻辑流向明显 调用方便  但iOS的版本非常不友好 界面莫名其妙 功能封装不够明确 内在逻辑调试很不方便  造成版本接入出现很多问题 已多次邮件反馈 浪费的大量的时间 】

本次更新的版本依然不能使用 在的issue补充截图 初步断定为podspec文件配置问题 导致项目目录和 实际显示目录不一致  造成文件引用问题  希望贵公司能尽快协助    

On Jan 28, 2019, at 07:23 PM, BaoYing-Fan <notifications@github.com> wrote:

线上项目拉下来编译可以通过，请问是那三个文件缺失，编译报什么错误？

**Comment by fanbaoying** [comment]
代码有没有拉取最新的，我拉取最新的代码测试是没问题的。

**Comment by KaneLanF** [comment]
我编译的就是今天拉取的代码

**Comment by KaneLanF** [comment]
方便的话 可否直接发一份你本地编译没问题的代码版本 邮件给我

**Comment by KaneLanF** [comment]
能否先打包一份 你本地编译通过的版本给我 Github的版本目前无法使用



On Mar 13, 2019, at 11:20 PM, BaoYing-Fan <notifications@github.com> wrote:

代码有没有拉取最新的，我拉取最新的代码测试是没问题的。

**Comment by fanbaoying** [comment]
代码已经发到你的邮箱

**Comment by KaneLanF** [comment]
1.邮箱没有看到附件 请问您发的是 shuizy@icloud.com 吗  我看了下没有附件
2.我自己调试了整理了下工程目录  目前还会报zwjLog找不到定义 ![](https://ws1.sinaimg.cn/large/006tKfTcgy1g12caz1ra6j30q209k754.jpg)

**Comment by fanbaoying** [comment]
是的，发的就是shuizy@icloud.com这个邮箱，你提供的另外一个邮箱也发了。

**Comment by KaneLanF** [comment]
[EspBlufiV1.1.zip](https://github.com/EspressifApp/EspBlufiForiOS/files/2976222/EspBlufiV1.1.zip)
这个版可以正常使用  通讯加密逻辑需要自己封装。
